name: build-test
on:
  push:
    branches:
      - main
      - develop
      - kb/*
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os: [ubuntu-latest]
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        id: "auth"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Run cloudsql plugin stests
        run: go test plugins/database/cloudsql
      - name:  Build vault
        run: go build -o cloudsql-database-plugin-iap-vault-plugin_${GOOS}_${GOARCH}
        working-directory: plugins/database/cloudsql/cloudsql-database-plugin
        env:
          GOOS: "${{ matrix.goos }}"
          GOARCH: "${{ matrix.goarch }}"
      - name: Smoke test cloudsql plugin
        run: |
          


