name: build-test
on:
  push:
    branches:
      - main
      - develop
      - kb/*
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os: [ubuntu-latest]
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go version
      - name:  Build vault
        run: go build ./plugins/database/postgresql/postgresql-database-plugin -o cloudsql-iap-vault-plugin_$GOOS_$GOARCH
        env:
          GOOS: "{{ matrix.goos }}"
          GOARCH: "{{ matrix.goarch }}"
